name: "Release {version}"
tag_template: "v{version}"
template: |
  ## What's Changed
  {changes}

  ## New Features
  {new_features}

  ## Bug Fixes
  {bug_fixes}

  ## Known Issues
  {known_issues}

  ## Improvements/Enhancements
  {improvements}
